version: '3.8'

services:
  sms-gateway:
    build: .
    container_name: sms-gateway
    ports:
      - "5000:5000"
    devices:
      - "/dev/ttyUSB2:/dev/ttyUSB2" # Adjust based on your modem's device name
    restart: always