version: '3.8'

services:
  sms-gateway:
    build: .
    container_name: sms-gateway
    ports:
      - "5001:5000"  # Changed to 5001 to avoid conflicts
    devices:
      - "/dev/ttyUSB2:/dev/ttyUSB2"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - TZ=Indian/Antananarivo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3